#!/bin/bash
#BSUB -J STEP10
#BSUB -P acc_Itan_lab
#BSUB -q private
#BSUB -R rusage[mem=10000]
#BSUB -R span[hosts=1]
#BSUB -n 20
#BSUB -W 48:00
#BSUB -o ./std/%J_STEP10.stdout
#BSUB -eo ./std/%J_STEP10.stderr
#BSUB -L /bin/bash

source ./STEP0.sh
cd $DIR
mkdir STEP10_out

ml python/3.8.2

python $DIR/STEP10.py $DIR/STEP4_1_out/vep_${NAME}_4_1.csv /sc/arion/projects/Itan_lab/minju/annotations/sources/vep_input/step9_input $DIR/STEP10_out/vep_${NAME}_10.csv





























































