#!/bin/bash
#BSUB -J STEP15
#BSUB -P acc_Itan_lab
#BSUB -q private
#BSUB -R rusage[mem=10000]
#BSUB -R span[hosts=1]
#BSUB -n 20
#BSUB -W 48:00
#BSUB -o ./std/%J_STEP15.stdout
#BSUB -eo ./std/%J_STEP15.stderr
#BSUB -L /bin/bash


source ./STEP0.sh
cd $DIR
mkdir STEP15_out


ml python/3.8.2
# automatically export variables
set -a
. ./STEP0.sh
exec python ./STEP15.py

cd $DIR/STEP15_out

cut -d, -f1 --complement vep_${NAME}_15.csv > vep_${NAME}_15.csv
