#!/bin/bash
#BSUB -J STEP12
#BSUB -P acc_Itan_lab
#BSUB -q private
#BSUB -R rusage[mem=10000]
#BSUB -R span[hosts=1]
#BSUB -n 20
#BSUB -W 48:00
#BSUB -o ./std/%J_STEP12.stdout
#BSUB -eo ./std/%J_STEP12.stderr
#BSUB -L /bin/bash


source ./STEP0.sh
cd $DIR/STEP11_out

cut -d, -f1 --complement 11_${NAME}_fix.csv > 11_${NAME}_mod.csv
cut -d, -f1 --complement 11_${NAME}_mod.csv > vep_${NAME}_11.csv

cd $DIR
mkdir STEP12_out

ml python/3.8.2
# automatically export variables
set -a
. ./STEP0.sh
exec python ./STEP12.py





















































                 
