#!/bin/bash
#BSUB -J STEP13
#BSUB -P acc_Itan_lab
#BSUB -q private
#BSUB -R rusage[mem=50000]
#BSUB -R span[hosts=1]
#BSUB -n 23
#BSUB -W 48:00
#BSUB -o ./std/%J_STEP13.stdout
#BSUB -eo ./std/%J_STEP13.stderr
#BSUB -L /bin/bash

source ./STEP0.sh
cd $DIR/STEP12_out
cut -d, -f1 --complement 12_${NAME}.csv > vep_${NAME}_12.csv

cd $DIR
mkdir STEP13_out


ml python/3.8.2
# automatically export variables
set -a
. ./STEP0.sh
exec python ./STEP13.py



















































