#!/bin/bash
#BSUB -J STEP4_2
#BSUB -P acc_Itan_lab
#BSUB -q private
#BSUB -R rusage[mem=10000]
#BSUB -R span[hosts=1]
#BSUB -n 11
#BSUB -W 48:00
#BSUB -o ./std/%J_STEP4_2.stdout
#BSUB -eo ./std/%J_STEP4_2.stderr
#BSUB -L /bin/bash

source ./STEP0.sh
cd $DIR
mkdir STEP4_2_out

ml python/3.8.2

python $DIR/STEP4_2.py $DIR/STEP3_out/vep_${NAME}_3.tsv /sc/arion/projects/Itan_lab/minju/annotations/sources/vep_input $DIR/STEP4_2_out/vep_${NAME}_4_2.csv






















































