#!/bin/bash
#BSUB -J STEP3
#BSUB -P acc_Itan_lab
#BSUB -q private
#BSUB -R rusage[mem=10000]
#BSUB -R span[hosts=1]
#BSUB -n 20
#BSUB -W 168:00
#BSUB -o ./std/%J_STEP3.stdout
#BSUB -eo ./std/%J_STEP3.stderr
#BSUB -L /bin/bash

source ./STEP0.sh
cd $DIR
mkdir STEP3_out

ml python/3.8.2
set -a
. ./STEP0.sh
python STEP3.py $DIR/STEP2_out/vep_${NAME}_2.tsv $DIR/STEP2_out/vep_${NAME}_2_header.txt $DIR/STEP3_out/vep_pre_${NAME}_3 $DIR/STEP3_out/vep_${NAME}_3.csv
